package com.tolgayakar.receipt_manager.Model;

import java.time.Instant;

import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

@Entity
public class Receipt {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "file_path")
    private String filePath;
    private String name;
    private String description;

    /**
     * Generated annotation is used for telling Hibernate that this value is db generated value, this value is generated by db when inserting a value to db.
     * Normally, Hibernate does not know this value generated by id. So after calling save(), it cannot obtain the value from the db, it is still a null value for it.
     * Hibernate only knows it should not send the value the db if insertable is set to false
    */
    @Generated(event = EventType.INSERT)
    /**
     * In sql file, this field is specified as not null. But Hibernate does not know about this info so it tries to send createdAt values as null.
     * This situation causes errors. To prevent that, insertable value should be set to false.
     */ 
    @Column(name = "created_at", insertable = false, updatable = false)
    private Instant createdAt;
    @Column(name = "is_deleted")
    private Boolean isDeleted;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private RmUser user;

    public Long getId() {
        return id;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String desc){
        this.description = desc;
    }

    public String getDescription() {
        return description;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Boolean getDeleted() {
        return isDeleted;
    }

    public void setUser(RmUser user) {
        this.user = user;
    }

    public RmUser getUser() {
        return user;
    }
}
