services:
  db:
    container_name: rm-postgres
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    container_name: rm-redis
    image: redis:8
    ports:
      - "6379:6379"
  backend:
    container_name: rm-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2

volumes:
  postgres_data:
  maven_cache: